server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: goal-service
  redis:
    host: ${REDIS_HOST:redis-service}
    port: ${REDIS_PORT:6379}
  kafka:
    kafka-server: ${KAFKA_BOOTSTRAP_SERVERS:kafka-service:9092}
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT:3306}/${DB_NAME:workforce}?useSsl=true&trustServerCertificate=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

jwt:
  expirationAt: 30
  secretKeyAt: ${JWT_SECRET_AT}
  expirationRt: 1440
  secretKeyRt: ${JWT_SECRET_RT}

aws:
  region: ${AWS_REGION:ap-northeast-2}
  s3:
    bucket: ${AWS_S3_BUCKET:workforce-profiles}
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}

# Eureka 비활성화 (K8s Service DNS 사용)
eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
