# Ingress Controller 사전 설치 필요:
# kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.1/deploy/static/provider/aws/deploy.yaml
#
# 흐름: AWS LB → Ingress Controller Pod → Ingress → gateway-service

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: workforce-ingress
  namespace: 4team
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - "server.workforcehr.shop"
      secretName: server-workforcehr-shop-tls
  rules:
    - host: server.workforcehr.shop
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: 80
