server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: search-service
  redis:
    host: ${REDIS_HOST:redis-service}
    port: ${REDIS_PORT:6379}
  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://elasticsearch-service:9200}
  kafka:
    kafka-server: ${KAFKA_BOOTSTRAP_SERVERS:kafka-service:9092}
    consumer:
      group-id: search-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT:3306}/${DB_NAME:workforcehr}?useSsl=true&trustServerCertificate=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true

aws:
  region: ${AWS_REGION:ap-northeast-2}
  s3:
    bucket: ${AWS_S3_BUCKET:workforce-profiles}
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}

# Eureka 비활성화 (K8s Service DNS 사용)
eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
